[Registration]
# Should users be required to verify their E-Mail address with a code before they can log in?
EmailVerificationRequired = false
# If EmailDomainWhitelist is true, only users with E-Mail addresses from the domains in AllowedEmailDomains will be allowed to register.
EmailDomainWhitelist = true
AllowedEmailDomains = [
	# Public providers
	"gmail.com", "outlook.com", "icloud.com", "yahoo.com", "yandex.com",
	"yandex.ru", "gmx.com", "spectrum.net", "comcast.net", "aol.com",
	"proton.me", "protonmail.com", "tutanota.com", "fastmail.fm",
	"mail.com", "email.com", "protonmail.ch", "googlemail.com", "gmx.de",
	"hotmail.com", "live.com", "msn.com", "mail.ru", "web.de", "t-online.de",
	# CollabVM and friends
	"computernewb.com", "elijahr.dev", "darkok.xyz", "kevinthe.horse", "kevinhosting.xyz", "ziad87.net", "mattx.cloud", "mdmck10.xyz", "retromail.me", "madz258.top",
]

[Accounts]
# The maximum number of sessions a user can have at once.
MaxSessions = 10
# The number of days a session can be inactive before it is deleted.
SessionExpiryDays = 30

[CollabVM]
# The key used by the CollabVM server to authenticate with the auth server.
SecretKey = "hunter2"

[HTTP]
# The address and port the HTTP server should listen on.
Host = "127.0.0.1"
Port = 5858
# If true, the server will use the X-FORWARDED-FOR header to get the client's IP address.
# This is required when you are using nginx or another reverse proxy (which you should be doing).
UseXForwardedFor = true
# If UseXForwardedFor is true, this is the list of trusted proxies that are allowed to set the X-FORWARDED-FOR header.
TrustedProxies = ["127.0.0.1"]

[MySQL]
Host = "127.0.0.1"
Username = "root"
Password = "hunter2"
Database = "AuthDatabase"

[SMTP]
# If true, E-Mail support will be enabled.
# This is required for account verification and password reset functionality.
Enabled = false
# The SMTP server and credentials to use for sending E-Mails.
Host = "localhost"
Port = 587
Username = "noreply@example.com"
Password = "hunter2"
FromName = "CollabVM"
FromEmail = "noreply@example.com"
# The subject and body of the E-Mail sent to users when they need to verify their E-Mail address.
VerificationCodeSubject = "CollabVM Account Verification"
VerificationCodeBody = """
Howdy! Someone (probably you) has tried to create a CollabVM account with this E-Mail. If this was you, your verification code is: $CODE

If this was not you, someone probably entered your e-mail by mistake. If this is the case, you can safely ignore this e-mail.
"""
# The subject and body of the E-Mail sent to users when they need to reset their password.
ResetPasswordSubject = "CollabVM Password Reset"
ResetPasswordBody = """
Howdy, $USERNAME! Someone (probably you) has sent a request to reset the password to your CollabVM account with this E-Mail. If this was you, your verification code is: $CODE

If this was not you, disregard this E-Mail and your password will remain unchanged. Do not share this code with anyone.
"""

[hCaptcha]
# If true, hCaptcha will be used for the registration, login, and password reset forms.
Enabled = false
# The hCaptcha site key and secret key.
Secret = ""
SiteKey = ""


