<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>false</PublishAot>
        <RootNamespace>Computernewb.CollabVMAuthServer</RootNamespace>
        <Company>Computernewb Development Team</Company>
        <AssemblyVersion>1.1</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
      <PackageReference Include="MailKit" Version="4.4.0" />
      <PackageReference Include="MySqlConnector" Version="2.3.6" />
      <PackageReference Include="Samboy063.Tomlet" Version="5.3.1" />
    </ItemGroup>

</Project>
