<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>false</PublishAot>
        <RootNamespace>Computernewb.CollabVMAuthServer</RootNamespace>
        <Company>Computernewb Development Team</Company>
        <AssemblyVersion>1.1</AssemblyVersion>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
      <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
      <PackageReference Include="MailKit" Version="4.12.0" />
      <PackageReference Include="MySqlConnector" Version="2.4.0" />
      <PackageReference Include="Samboy063.Tomlet" Version="6.0.0" />
    </ItemGroup>

</Project>
