// <auto-generated />
using System;
using Computernewb.CollabVMAuthServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Computernewb.CollabVMAuthServer.Database.Migrations
{
    [DbContext(typeof(CollabVMAuthDbContext))]
    [Migration("20250505224256_InitialDbModel")]
    partial class InitialDbModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.Bot", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<uint>("CvmRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("cvm_rank")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("owner");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("token")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Owner" }, "owner");

                    b.HasIndex(new[] { "Token" }, "token")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("bots", (string)null);
                });

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.IpBan", b =>
                {
                    b.Property<byte[]>("Ip")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("ip");

                    b.Property<DateTime>("BannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("banned_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("BannedBy")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("banned_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Ip")
                        .HasName("PRIMARY");

                    b.ToTable("ip_bans", (string)null);
                });

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.Session", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(32)
                        .HasColumnType("char(32)")
                        .HasColumnName("token")
                        .IsFixedLength();

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<byte[]>("LastIp")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("last_ip");

                    b.Property<DateTime>("LastUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_used")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Token")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "username");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<bool>("Banned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("banned");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<uint>("CvmRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("cvm_rank")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool>("Developer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("developer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("email_verification_code")
                        .IsFixedLength();

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_verified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("password_reset_code")
                        .IsFixedLength();

                    b.Property<byte[]>("RegistrationIp")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("registration_ip");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.Bot", b =>
                {
                    b.HasOne("Computernewb.CollabVMAuthServer.Database.Schema.User", "OwnerNavigation")
                        .WithMany("Bots")
                        .HasForeignKey("Owner")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bots_ibfk_1");

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.Session", b =>
                {
                    b.HasOne("Computernewb.CollabVMAuthServer.Database.Schema.User", "UsernameNavigation")
                        .WithMany("Sessions")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sessions_ibfk_1");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("Computernewb.CollabVMAuthServer.Database.Schema.User", b =>
                {
                    b.Navigation("Bots");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
